apiVersion: v1
kind: Pod
metadata:
    name: postgres-app
    labels:
      name: postgres-app
      app: demo-voting-app
spec:
  containers:
    - name: postgres-container
      image: postgres
      ports:
      - containerPort: 5432
      env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"