apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels: 
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
    name: postgres-app
    app: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432

