apiVersion: v1
kind: Pod
metadata:
    name: redis-app
    labels:
      name: redis-app
      app: demo-voting-app
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
      - containerPort: 6379