apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels: 
    name:  redis-service
    app: demo-voting-app
spec:
  selector:
    name: redis-app
    app: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379

